title: Yingqi Xiao
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://https://www.linkedin.com/in/yingqi-xiao/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

